server:
  port: 8484
spring:
  application:
    name: airbnb-xa
  jta:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
jwt:
  secret: 87a9c0cec245892d8359c17b6cdfe674823bc66ede0900b1ee33de2c1e2f26b349647497c3a5858f454b63210b2e2cb3f924236537da067d8ba5d2f00240c59d
  lifetime: 1209600000
credentials:
  admin:
    username: admin
    password: administrator
logging:
  level:
    root: info
